import { STAMP_STYLE_PRESETS, type StampStyle } from "./stamp-prompts";

interface GenerateStampResult {
	imageData: Uint8Array;
	mimeType: string;
	enhancedPrompt: string;
}

/**
 * Enhance a user's rough prompt into a detailed stamp illustration prompt.
 * Uses CF Workers AI Llama 3.1 8B (free) to auto-tune the prompt.
 */
async function enhancePrompt(
	ai: Ai,
	userPrompt: string,
	style: StampStyle,
): Promise<string> {
	const preset = STAMP_STYLE_PRESETS[style];

	const systemPrompt = `You are a prompt engineer for an AI image generator that creates postage stamp illustrations.
Your job: take the user's rough idea and output a single, detailed image generation prompt.

Rules:
- Output ONLY the prompt text, no explanation
- Keep it under 200 words
- Always include: "postage stamp", "perforated edges", "illustration"
- Include specific art style details: ${preset.prompt}
- Add details about composition, colors, textures, lighting
- Never include text/words/numbers on the stamp
- Make it vivid and specific for best image generation results`;

	const response = (await ai.run(
		// @ts-expect-error — model name valid at runtime, types may lag
		"@cf/meta/llama-3.1-8b-instruct",
		{
			messages: [
				{ role: "system", content: systemPrompt },
				{ role: "user", content: userPrompt },
			],
			max_tokens: 300,
			temperature: 0.7,
		},
	)) as { response?: string };

	return response.response?.trim() || buildFallbackPrompt(userPrompt, style);
}

/**
 * Fallback prompt builder if LLM enhancement fails.
 */
function buildFallbackPrompt(userPrompt: string, style: StampStyle): string {
	const preset = STAMP_STYLE_PRESETS[style];
	return `Postage stamp illustration, ${preset.prompt}. Subject: ${userPrompt}. Perforated edges, no text, square format, hand-crafted artistic feel, limited color palette.`;
}

/**
 * Generate a stamp using CF Workers AI (free).
 * Two-stage: LLM enhances prompt → Flux Schnell generates image.
 */
export async function generateStamp(
	ai: Ai,
	userPrompt: string,
	style: StampStyle = "vintage",
): Promise<GenerateStampResult> {
	// Stage 1: Auto-enhance prompt with LLM
	let enhancedPrompt: string;
	try {
		enhancedPrompt = await enhancePrompt(ai, userPrompt, style);
	} catch {
		enhancedPrompt = buildFallbackPrompt(userPrompt, style);
	}

	// Stage 2: Generate image with Flux Schnell
	const response = (await ai.run("@cf/black-forest-labs/flux-1-schnell", {
		prompt: enhancedPrompt,
		steps: 8,
	})) as { image?: string };

	if (!response.image) {
		throw new Error("No image generated by Flux Schnell.");
	}

	const imageBytes = Uint8Array.from(atob(response.image), (c) =>
		c.charCodeAt(0),
	);

	return {
		imageData: imageBytes,
		mimeType: "image/jpeg",
		enhancedPrompt,
	};
}
