import { buildStampPrompt, type StampStyle } from "./stamp-prompts";

interface GenerateStampResult {
	imageData: Uint8Array;
	mimeType: string;
}

/**
 * Generate a stamp image using Google Imagen 4 Fast.
 * $0.02/image — best quality-to-price for artistic illustrations.
 */
export async function generateStamp(
	apiKey: string,
	userPrompt: string,
	style: StampStyle = "vintage",
): Promise<GenerateStampResult> {
	const fullPrompt = buildStampPrompt(userPrompt, style);

	const response = await fetch(
		"https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-fast-generate-001:predict",
		{
			method: "POST",
			headers: {
				"x-goog-api-key": apiKey,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				instances: [{ prompt: fullPrompt }],
				parameters: {
					sampleCount: 1,
					aspectRatio: "1:1",
				},
			}),
		},
	);

	if (!response.ok) {
		const error = await response.text();
		throw new Error(`Imagen API error: ${response.status} — ${error}`);
	}

	const data = (await response.json()) as {
		predictions?: Array<{ bytesBase64Encoded: string; mimeType?: string }>;
	};

	const prediction = data.predictions?.[0];
	if (!prediction?.bytesBase64Encoded) {
		throw new Error("No image generated by Imagen.");
	}

	const imageBytes = Uint8Array.from(atob(prediction.bytesBase64Encoded), (c) =>
		c.charCodeAt(0),
	);

	return {
		imageData: imageBytes,
		mimeType: prediction.mimeType || "image/png",
	};
}
