export function Footer() {
	return (
		<footer className="border-t border-stone-200/50 mt-auto">
			<div className="max-w-5xl mx-auto px-4 py-8 text-center text-sm text-stone-500 font-sans">
				<p>Made with AI. Stamps generated by Gemini.</p>
				<p className="mt-1">
					<a
						href="https://stamp.builder"
						className="hover:text-stone-700 transition"
					>
						stamp.builder
					</a>
				</p>
			</div>
		</footer>
	);
}
