import { describe, expect, it, vi } from "vitest";
import { createMockAi } from "@/test-utils";
import { generateStamp } from "../generate-stamp";
import { STAMP_STYLE_PRESETS } from "../stamp-prompts";

describe("generateStamp", () => {
	it("returns image data and enhanced prompt", async () => {
		const mockAi = createMockAi(
			"A naive folk art postage stamp of a cat with stippled shading",
			btoa("fake-image-data"),
		);

		const result = await generateStamp(mockAi, "a cat", "vintage");

		expect(result.imageData).toBeInstanceOf(Uint8Array);
		expect(result.imageData.length).toBeGreaterThan(0);
		expect(result.mimeType).toBe("image/jpeg");
		expect(result.enhancedPrompt).toContain("folk art");
	});

	it("uses fallback prompt when LLM fails", async () => {
		const mockAi = {
			run: vi.fn().mockImplementation((model: string) => {
				if (model.includes("qwen")) {
					return Promise.reject(new Error("LLM unavailable"));
				}
				if (model.includes("flux")) {
					return Promise.resolve({ image: btoa("image") });
				}
			}),
		} as unknown as Ai;

		const result = await generateStamp(mockAi, "a dog", "modern");

		expect(result.enhancedPrompt).toContain("naive folk art");
		expect(result.enhancedPrompt).toContain("a dog");
	});

	it("throws when Flux returns no image", async () => {
		const mockAi = createMockAi("enhanced prompt", null);

		await expect(generateStamp(mockAi, "test", "vintage")).rejects.toThrow(
			"No image generated",
		);
	});

	it("uses Flux 2 Klein 9B model when hd is true", async () => {
		const mockAi = createMockAi(
			"A naive folk art postage stamp of a cat",
			btoa("hd-image-data"),
		);

		const result = await generateStamp(mockAi, "a cat", "vintage", true);

		expect(result.imageData).toBeInstanceOf(Uint8Array);
		expect(result.imageData.length).toBeGreaterThan(0);
		expect(result.mimeType).toBe("image/jpeg");

		// Verify the HD model was called with correct params
		const calls = vi.mocked(mockAi.run).mock.calls;
		const fluxCall = calls.find(
			(c) => typeof c[0] === "string" && c[0].includes("flux"),
		);
		expect(fluxCall).toBeDefined();
		expect(fluxCall?.[0]).toContain("flux-2-klein-9b");
	});

	it("uses Flux 1 Schnell model when hd is false", async () => {
		const mockAi = createMockAi(
			"A naive folk art postage stamp of a cat",
			btoa("standard-image-data"),
		);

		await generateStamp(mockAi, "a cat", "vintage", false);

		const calls = vi.mocked(mockAi.run).mock.calls;
		const fluxCall = calls.find(
			(c) => typeof c[0] === "string" && c[0].includes("flux"),
		);
		expect(fluxCall).toBeDefined();
		expect(fluxCall?.[0]).toContain("flux-1-schnell");
	});

	it("throws HD-specific error when Flux 2 Klein returns no image", async () => {
		const mockAi = createMockAi("enhanced prompt", null);

		await expect(
			generateStamp(mockAi, "test", "vintage", true),
		).rejects.toThrow("No image generated by Flux 2 Klein");
	});

	it("works with all style presets", async () => {
		const styles = Object.keys(STAMP_STYLE_PRESETS) as Array<
			keyof typeof STAMP_STYLE_PRESETS
		>;

		for (const style of styles) {
			const mockAi = createMockAi(`A ${style} stamp`, btoa("img"));
			const result = await generateStamp(mockAi, "subject", style);
			expect(result.imageData).toBeInstanceOf(Uint8Array);
		}
	});
});

describe("reference-based generation", () => {
	it("passes referenceDescription to enhancePrompt", async () => {
		const mockAi = createMockAi(
			"A stamp based on the reference",
			btoa("fake-image-data"),
		);
		const result = await generateStamp(
			mockAi,
			"",
			"vintage",
			false,
			"A cat sitting on a chair",
		);
		expect(result.enhancedPrompt).toBeDefined();
		// Verify the LLM was called with reference description
		const calls = vi.mocked(mockAi.run).mock.calls;
		const qwenCall = calls.find(
			(c) => typeof c[0] === "string" && c[0].includes("qwen"),
		);
		expect(qwenCall).toBeDefined();
		const messages = (qwenCall?.[1] as Record<string, unknown>)
			?.messages as Array<{ role: string; content: string }>;
		const userMsg = messages?.find((m) => m.role === "user");
		expect(userMsg?.content).toContain("Reference image description");
		expect(userMsg?.content).toContain("A cat sitting on a chair");
	});

	it("uses fallback prompt with reference when LLM fails", async () => {
		const mockAi = {
			run: vi.fn().mockImplementation((model: string) => {
				if (model.includes("qwen"))
					return Promise.reject(new Error("LLM fail"));
				if (model.includes("flux"))
					return Promise.resolve({ image: btoa("img") });
			}),
		} as unknown as Ai;

		const result = await generateStamp(
			mockAi,
			"",
			"vintage",
			false,
			"A sunset over mountains",
		);
		expect(result.enhancedPrompt).toContain("Based on reference");
		expect(result.enhancedPrompt).toContain("A sunset over mountains");
	});

	it("works with both reference and user prompt", async () => {
		const mockAi = createMockAi("Combined stamp prompt", btoa("img"));
		const result = await generateStamp(
			mockAi,
			"make it blue",
			"modern",
			false,
			"A cat on a chair",
		);
		expect(result.enhancedPrompt).toBeDefined();
	});
});
